<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js') ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/goo.rs.js') ?>
        <script>
        
            
            
        </script>
        <style>
            
        </style>
    </head>
    <body>
        <div class="line"></div>
        <div class="navbar">
            <div class="nav">
                
                <div class="logo module">
                    <img src="/img/url-shortener.png" title="URL Shortener" alt="URL SHortener" />
                </div>
                <div class="social" >
                    <img src="/img/social/twitter.png" alt="Goo.rs Twitter account" title="Goo.rs Twitter account" onclick="window.location.href ='https://twitter.com/preg_match' " />
                    <img src="/img/social/plus.png" alt="Goo.rs Google plus account" title="Goo.rs Google plus account" onclick="window.location.href = 'https://plus.google.com/107267331818493393843'" />
                    
                </div>
                
                <div class="menu">
                    <ul>
                        <li class="<?php echo ($_SERVER['REQUEST_URI'] == '/' ? 'active':''); ?>"><a href="/">Home</a></li>
                        <li><a target="_blank" href="https://chrome.google.com/webstore/detail/goors-url-shortener/kmochnpildobbcendaeepmlabahghmgk">Chrome extension</a></li>
                        <li class="<?php echo ($_SERVER['REQUEST_URI'] == '/tf-idf' ? 'active':''); ?>"><a href="/tf-idf">Human readable?</a></li>
                        <li class="<?php echo ($_SERVER['REQUEST_URI'] == '/api/index' ? 'active':''); ?>"><a href="/api/index">API</a></li>
                    </ul>
                    <div style="clear: both;"></div>
                </div>
                
            </div>
            <div style="clear: both;"></div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            
        </div>
        <div class="footer module">
            <div class="api">
                
                <img src="/img/api.png" title="URL Shortener API"  alt="URL Shortener API" onclick="window.location.href= '/api/index';" style="cursor: pointer;" />
                <span class="copyright">
                    &copy; 2013 Under <a href="http://opensource.org/licenses/CDDL-1.0" target="_blank">Common Development and Distribution License</a>
                </span>
            </div>
        </div>
    </body>
</html>
