<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    
    'Api\Keyword\Keyword' => __DIR__ . '/../../library/Keyword/Keyword.php',
    'Api\Human\Human' => __DIR__ . '/../../library/Human/Human.php',
    
);
