<div class="form-holder">
    <div class="short-link module">
        <span>http://goo.rs/..</span>
    </div>
    <div class="long-link-input module">
        
        <input value="Paste your long url here" id="longurl"  />
    </div>
    <div class="form-actions module">
        <input type="submit" value="Make it short" class="make-it-short" />
        <label>
            <input type="checkbox" class="css-checkbox human"  /> 
            <label class="css-label">
                but make human readable link
            </label>
        </label>
    </div>
    
</div>